apiVersion: v1
kind: Service
metadata:
  name: {{ include "servarr.fullname" . }}
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{ if eq .Values.service.type "ExternalName" }}
  externalName: {{ .Values.service.externalName }}
  {{ end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "servarr.selectorLabels" . | nindent 4 }}