name: ci

on:
  pull_request:

env:
  helm-version: "v3.12.2"
  kubeval-version: "v0.16.1"

jobs:
  kubeval-chart:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        k8s:
          - v1.21.14
          - v1.22.17
          - v1.23.17
          - v1.24.15
          - v1.25.11
          - v1.26.6
          - v1.27.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh

  test-chart:
    name: test-chart
    runs-on: ubuntu-latest
    needs:
      - kubeval-chart
    strategy:
      matrix:
        k8s:
          - v1.21.14
          - v1.22.17
          - v1.23.17
          - v1.24.15
          - v1.25.11
          - v1.26.6
          - v1.27.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create kind ${{ matrix.k8s }} cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.8.0
        with:
          node_image: kindest/node:${{ matrix.k8s }}
          kubectl_version: ${{ matrix.k8s }}

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }}